config/routes.rb
Rails.application.routes.draw do
  get 'session/login'
  root 'task#input'
  get 'task/output'
  get 'session/create'
  get 'session/logout'
  post 'session/create'
  resources :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password
    validates_uniqueness_of :username
    validates_presence_of :username
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    include SessionHelper
    before_action :require_login

    def require_login
      redirect_to session_login_path unless signed_in?
    end
end

app/controllers/session_controller.rb
class SessionController < ApplicationController
  skip_before_action :require_login, only: %i[login create]
  before_action :not_found, only: [:create]
  def login
  end

  def create
    user = User.find_by_username(params[:username])
    if user&.authenticate(params[:password])
      sign_in user
      redirect_to root_path
    else
      redirect_to session_login_path
    end
  end

  def logout
    sign_out
    redirect_to session_login_url
  end

  private
  
  def not_found
    if !User.find_by_username(params[:username])
      flash[:error] = 'Ошибка: пользователь не найден.'
      redirect_to session_login_path
    elsif !User.find_by_username(params[:username]).authenticate(params[:password])
      flash[:error] = 'Ошибка: неверный пароль.'
      redirect_to session_login_path
    end
  end

end

app/controllers/task_controller.rb
# frozen_string_literal: true

# Controller class for task
class TaskController < ApplicationController
  before_action :raise_error, only: [:output]

  def input; end

  def output
    @max_seg = 0
    str = params[:array]
    arr = str.split(' ').map(&:to_i)
    @segments = get_segments(arr)
    @max_seg = (@segments.max_by { |elem| elem[:length] })[:segment] unless @segments.nil? || @segments.empty?
    @count = @segments.length
  end

  private

  def perfect?(num)
    summ = 0
    ans = false
    (1...num).each do |i|
      summ += i if (num % i).zero?
    end
    ans = true if (summ == num) && num.positive?
    ans
  end

  def get_segments(array)
    result = []
    len = 0
    seg = []
    array.each do |elem|
      if perfect?(elem)
        len += 1
        seg.append(elem)
      else
        result.append({ length: len, segment: seg.join(' ') }) if len.positive?
        len = 0
        seg = []
      end
    end
    result.append({ length: len, segment: seg.join(' ') }) if len.positive?
    result
  end

  def raise_error
    if params[:array].nil? || params[:array].empty?
      flash[:error] = 'Ошибка: параметры не должны быть пустыми.'
      redirect_to root_path
    elsif !params[:array].match(/^( ?-?\d)+$/)
      flash[:error] = 'Ошибка: параметры введены некорректно.'
      redirect_to root_path
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[ show edit update destroy ]
  skip_before_action :require_login, only: %i[create new edit]
  # GET /users or /users.json
  def index
    @users = User.all
  end

  # GET /users/1 or /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users or /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        sign_in @user
        format.html { redirect_to user_url(@user), notice: "User was successfully created." }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to user_url(@user), notice: "User was successfully updated." }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url, notice: "User was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:username, :password)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/session_helper.rb
module SessionHelper
    def signed_in?
        !current_user.nil?
    end

    def sign_in(user)
        cookies.signed[:user_id] = { value: user.id, expires: 7.days }
        @current_user = user
    end

    def sign_out
        cookies.signed[:user_id] = nil
        @current_user = nil
    end

    def current_user
        @current_user ||= User.find_by(id: cookies.signed[:user_id])
    end
end

app/helpers/task_helper.rb
module TaskHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Lab12</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/session/login.html.erb
<h1>Войти</h1>
<%= form_with url: session_create_path, method: :post, local:true do |f| %>
    <%= f.label 'Имя пользователя:' %>
    <%= f.text_field :username, require: true %><br/>
    <%= f.label 'Пароль:' %>
    <%= f.password_field :password, require: true %><br/>
    <%= f.submit :password, value: 'Войти', require: true %>
<% end %>
<% unless flash[:error].nil? %>
    <p> <%= flash[:error] %> </p>  
<% end %>
<%=link_to 'Регистрация', new_user_path%>

app/views/task/input.html.erb
<h1>Task#input</h1>
<h1>Задание</h1>
<p>Дано натуральное число n и целые числа a1 , a2 , . . . an . Написать про-</br>
грамму, определяющую, есть ли среди заданной последовательности чи-</br>
сел отрезки (непрерывные подпоследовательности), состоящие из совер-</br>
шенных чисел. Если есть, то подсчитать их количество и определить са-</br>
мый длинный из отрезков. Вывести на печать все отрезки, самый длин-</br>
ный из них и количество искомых отрезков. Если таких отрезков нет, то</br>
соответствующее сообщение. При составлении программы использовать</br>
функции. (Совершенным числом называется целое число, которое равно</br>
сумме своих сомножителей, кроме его самого).</br></p>

<%= form_with url: "/task/output", method: :get do |form| %>
  <%= form.label :array, "Последовательность целых чисел: " %>
  <%= form.text_field :array %>
  <%= form.submit "Найти отрезки" %>
  </br>
<% end %>
<% unless flash[:error].nil? %>
<p> <%= flash[:error] %> </p>  
<% end %>
<p>Пример: -1 21 6 28 0 8128 -6 8128 496 28 7 1 6 6</p>
<%=link_to 'Выйти из учетной записи', session_logout_path%>
<%=link_to 'Просмотреть базу с пользователями', :users%>

app/views/task/output.html.erb
<h1>Task#show</h1>
<p id="count">Количество отрезков: <%= @count %></p>
<p id="max_seg">Самый длинный отрезок: <%= @max_seg %></p>
<table id ="segments" style="border: 1px solid black">
<tr><th>Длина</th><th>Отрезок</th></tr>
<% @segments.each do |seg| %>
    <tr><td><%= seg[:length] %></td><td><%= seg[:segment] %></td></tr>
<%end%>
<table>

<%= link_to 'Вернуться на страницу ввода', root_path%>

app/views/users/_form.html.erb
<%= form_with(model: user) do |form| %>
  <% if user.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :username, style: "display: block" %>
    <%= form.text_field :username %>
  </div>

  <div>
    <%= form.label :password, style: "display: block" %>
    <%= form.password_field :password %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/users/_user.html.erb
<div id="<%= dom_id user %>">
  <p>
    <strong>Username:</strong>
    <%= user.username %>
  </p>

  <p>
    <strong>Password digest:</strong>
    <%= user.password_digest %>
  </p>

</div>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render "form", user: @user %>

<br>

<div>
  <%= link_to "Show this user", @user %> |
  <%= link_to "Back to users", users_path %>
</div>

app/views/users/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Users</h1>

<div id="users">
  <% @users.each do |user| %>
    <%= render user %>
    <p>
      <%= link_to "Show this user", user %>
    </p>
  <% end %>
</div>

<%= link_to "Go back", root_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render "form", user: @user %>

<br>

<div>
  <%= link_to "Back to users", users_path %>
</div>

app/views/users/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @user %>

<div>
  <%= link_to "Edit this user", edit_user_path(@user) %> |
  <%= link_to "Back to users", users_path %>

  <%= button_to "Destroy this user", @user, method: :delete %>
  <%= link_to "Go back", root_path %>
</div>